<?php

namespace CRH\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getRandomComment($limit = 1)
    {
        
        //dump($this);
        $em = $this->_em;
        
        
        $sql = "SELECT * FROM comment c WHERE isapproved = true ORDER BY RAND() LIMIT " . $limit;

        $rsm = new ResultSetMappingBuilder($em);
        $rsm->addRootEntityFromClassMetadata('CRHWebBundle:Comment', 'c');
        
        $results = $this->_em->createNativeQuery($sql, $rsm)->getResult();
        return $results;
        
        
        
    }
}
