<?php

namespace CRH\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    
    public function getUpcomingEvents($limit = 3)
    {
        $qb = $this->createQueryBuilder('e');
        $dql = $qb->where('e.eventDate > CURRENT_DATE()')->orderBy('e.eventDate', 'ASC')->setMaxResults($limit)->getDQL();

        return $this->_em->createQuery($dql)->getResult();
    }
    
}
