<?php

namespace CRH\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FitnessTipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FitnessTipRepository extends EntityRepository
{
}
