<?php

namespace CRH\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * POI_TYPERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class POI_TYPERepository extends EntityRepository
{
}
