<?php

namespace CRH\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PointsOfInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointsOfInterestRepository extends EntityRepository
{
}
