<?php

namespace CRH\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Query\ResultSetMappingBuilder;


/**
 * TrailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrailRepository extends EntityRepository
{
    public function getRandomTrails($limit = 3)
    {
        
        
        $em = $this->_em;
        
        //The slide show requires a banner image and at least one smaller image for use on mobile, only select candidates
        $sql = "SELECT * FROM trail t WHERE bannerPhoto1 IS NOT NULL AND (photo1 IS NOT NULL OR photo2 IS NOT NULL OR photo3 IS NOT NULL OR photo4 IS NOT NULL) ORDER BY RAND() LIMIT " . $limit;

        $rsm = new ResultSetMappingBuilder($em);
        $rsm->addRootEntityFromClassMetadata('CRHWebBundle:Trail', 't');
        
        $results = $this->_em->createNativeQuery($sql, $rsm)->getResult();
        return $results;

    }
}